import chardet
import requests
import os
import re
import hashlib
import subprocess
import json
from typing import Optional, Dict, List, Tuple
from dataclasses import dataclass
from app.log import logger
import opencc
from .danmu_api import default_api as DanmuAPI

@dataclass
class VideoInfo:
    file_name: str
    file_hash: str
    file_size: int
    video_duration: int
    match_mode: str = "hashAndFileName"

class DanmuConverter:
    @staticmethod
    def convert_traditional_to_simplified(text: str) -> str:
        """
        将繁体中文转换为简体中文
        :param text: 要转换的文本
        :return: 转换后的简体中文文本
        """
        try:
            converter = opencc.OpenCC('t2s')  # t2s表示繁体转简体
            return converter.convert(text)
        except Exception as e:
            logger.error(f"繁体转简体失败: {e}")
            return text  # 如果转换失败，返回原文本

    @staticmethod
    def convert_timestamp(timestamp: float) -> str:
        timestamp = round(timestamp * 100.0)
        hour, minute = divmod(timestamp, 360000)
        minute, second = divmod(minute, 6000)
        second, centsecond = divmod(second, 100)
        return f'{int(hour)}:{int(minute):02d}:{int(second):02d}.{int(centsecond):02d}'

    @staticmethod
    def write_ass_head(f, width: int, height: int, fontface: str, fontsize: float, alpha: float, styleid: str):
        # 将透明度从0-1转换为0-255，并反转（因为ASS中0是完全不透明，255是完全透明）
        alpha_value = int((1 - alpha) * 255)
        f.write(
            f'''[Script Info]
; Script generated by Hankun 
; Super thanks to https://github.com/m13253/danmaku2ass and https://www.dandanplay.com/
Script Updated By: MoviePilot Danmu Plugin https://github.com/HankunYu/MoviePilot-Plugins
ScriptType: v4.00+
PlayResX: {width}
PlayResY: {height}
Aspect Ratio: {width}:{height}
Collisions: Normal
WrapStyle: 2
ScaledBorderAndShadow: yes
YCbCr Matrix: TV.601

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: {styleid}, {fontface}, {fontsize:.0f}, &H{alpha_value:02X}FFFFFF, &H{alpha_value:02X}FFFFFF, &H{alpha_value:02X}000000, &H{alpha_value:02X}000000, 0, 0, 0, 0, 100, 100, 0.00, 0.00, 1, {max(fontsize / 25.0, 1):.0f}, 0, 7, 0, 0, 0, 0

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
'''
        )

    @staticmethod
    def find_non_overlapping_track(tracks: Dict[int, float], current_time: float, max_tracks: int) -> int:
        possible_track = 1
        last_time_remain = 100.0
        for track in range(1, max_tracks + 1):
            if track not in tracks or current_time >= tracks[track]:
                return track
            time_remain = float(tracks[track]) - current_time
            if time_remain > last_time_remain:
                possible_track = track
        return possible_track

    @classmethod
    def convert_comments_to_ass(cls, comments: List[Dict], output_file: str, width: int, height: int, fontface: str,
                                fontsize: float, alpha: float, duration: float, convert_t_2_s: bool, subtitle_area_height: int = 200):
        styleid = 'Danmu'
        # 确保所有数值都是正确的类型
        width = int(width)
        height = int(height)
        fontsize = float(fontsize)
        subtitle_area_height = int(subtitle_area_height)
        
        # 调整最大轨道数，使弹幕更密集
        max_tracks = int((height - subtitle_area_height) / (fontsize * 0.8))
        scrolling_tracks = {}
        top_tracks = {}
        bottom_tracks = {}

        logger.info(f"{output_file} - 共匹配到{len(comments)}条弹幕。")
        
        with open(output_file, 'w', encoding='utf-8-sig') as f:
            cls.write_ass_head(f, width, height, fontface, fontsize, alpha, styleid)
            
            bottom_danmu_count = 0
            skipped_danmu_count = 0
            
            for comment in comments:
                try:
                    p = comment.get('p', '').split(',')
                    if len(p) < 3:
                        logger.warning(f"弹幕数据格式不正确: {comment}")
                        continue
                    
                    timeline = float(p[0])
                    pos = int(p[1])
                    color = int(p[2])
                    text = comment.get('m', '')
                    # 繁体转简体
                    if convert_t_2_s:
                        text = cls.convert_traditional_to_simplified(text)
                    user = str(p[3])

                    if not text:
                        continue
                        
                    start_time = cls.convert_timestamp(timeline)
                    end_time = cls.convert_timestamp(timeline + duration)
                    
                    gap = 1
                    text_width = len(text) * fontsize * 0.6
                    velocity = (width + text_width) / duration
                    leave_time = text_width / velocity + gap

                    color_hex = f'&H{color & 0xFFFFFF:06X}'
                    styles = ''
                    
                    if pos == 1:  # 滚动弹幕
                        track_id = cls.find_non_overlapping_track(scrolling_tracks, timeline, max_tracks)
                        scrolling_tracks[track_id] = timeline + leave_time
                        initial_y = (track_id - 1) * fontsize * 0.8 + 10
                        styles = f'\\move({width}, {initial_y}, {-len(text)*fontsize}, {initial_y})'
                    elif pos == 4:  # 底部弹幕
                        bottom_danmu_count += 1
                        track_id = cls.find_non_overlapping_track(bottom_tracks, timeline, max_tracks)
                        # 计算弹幕的垂直位置，使用更小的间距
                        bottom_position = height - (track_id - 1) * fontsize * 0.8
                        # 如果启用防遮挡且弹幕位置在字幕区域内，跳过该弹幕
                        if subtitle_area_height > 0 and bottom_position > (height - subtitle_area_height):
                            skipped_danmu_count += 1
                            continue
                        bottom_tracks[track_id] = timeline + duration
                        styles = f'\\an2\\pos({width/2}, {bottom_position})'
                    elif pos == 5:  # 顶部弹幕
                        track_id = cls.find_non_overlapping_track(top_tracks, timeline, max_tracks)
                        top_tracks[track_id] = timeline + duration
                        styles = f'\\an8\\pos({width/2}, {50 + (track_id - 1) * fontsize * 0.8})'
                    else:
                        styles = f'\\move(0, 0, {width}, 0)'

                    f.write(f'Dialogue: 0,{start_time},{end_time},{styleid},,0,0,0,,{{\\c{color_hex}{styles}}}{text}\n')
                except Exception as e:
                    logger.error(f"处理弹幕数据失败: {e}, 弹幕数据: {comment}")
                    continue
            
            logger.info(f'弹幕生成完成 - {output_file}')
            logger.info(f'底部弹幕统计 - 总数: {bottom_danmu_count}, 因防遮挡跳过: {skipped_danmu_count}')

class SubtitleProcessor:
    @staticmethod
    def get_video_streams(file_path: str) -> Dict:
        try:
            result = subprocess.run(
                ['ffprobe', '-v', 'error', '-print_format', 'json', '-show_format', '-show_streams', file_path],
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                universal_newlines=True
            )
            return json.loads(result.stdout) if result.returncode == 0 else {}
        except Exception as e:
            logger.error(f"获取视频流信息失败: {e}")
            return {}

    @staticmethod
    def extract_subtitles(file_path: str, output_file: str, stream_index: int) -> bool:
        try:
            result = subprocess.run(
                ['ffmpeg', '-i', file_path, '-map', f'0:{stream_index}', '-c:s', 'ass', output_file],
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                universal_newlines=True
            )
            return result.returncode == 0
        except Exception as e:
            logger.error(f"提取字幕失败: {e}")
            return False

    @classmethod
    def try_extract_sub(cls, file_path: str):
        streams_info = cls.get_video_streams(file_path)
        for stream in streams_info.get('streams', []):
            if stream.get('codec_type') == 'subtitle':
                stream_index = stream['index']
                base_name = os.path.splitext(file_path)[0]
                language = stream.get('tags', {}).get('language', 'unknown')
                
                if language not in ['zh', 'zho', 'chi', 'chs', 'cht', 'cn']:
                    continue
                    
                output_file = f"{base_name}.{language}.ass"
                if os.path.exists(output_file):
                    os.remove(output_file)
                    
                if cls.extract_subtitles(file_path, output_file, stream_index):
                    logger.info(f'成功提取内嵌字幕 - {output_file}')
                    break

    @staticmethod
    def find_subtitle_file(file_path: str) -> Optional[str]:
        filename = os.path.splitext(os.path.basename(file_path))[0]
        for root, _, files in os.walk(os.path.dirname(file_path)):
            for file in files:
                if (file.endswith(('.srt', '.ass', '.ssa')) and 
                    'danmu' not in file and 
                    file.startswith(filename)):
                    sub2 = os.path.join(root, file)
                    logger.info(f"找到字幕文件 - {sub2}")
                    return sub2
        logger.info("没找到字幕文件")
        return None

    @staticmethod
    def combine_sub_ass(sub1: str, sub2: str) -> bool:
        if not sub1 or not sub2:
            return False
        
        try:
            with open(sub1, 'r', encoding='utf-8-sig') as f:
                sub1_content = f.read()
            
            with open(sub2, 'rb') as f:
                raw_data = f.read()
                result = chardet.detect(raw_data)
                file_encoding = result['encoding']
            
            with open(sub2, 'r', encoding=file_encoding) as f:
                sub2_content = f.read()
                
            if os.path.splitext(sub2)[1].lower() in ['.ass', '.ssa']:
                sub1ResX = re.search(r"PlayResX:\s*(\d+)", sub1_content)
                sub2ResX = re.search(r"PlayResX:\s*(\d+)", sub2_content)

                fontSizeRatio = 1
                if sub1ResX and sub2ResX:
                    fontSizeRatio = int(sub1ResX.group(1)) / int(sub2ResX.group(1)) * 0.8

                format_match = re.search(r"Format:.+", sub2_content)
                if not format_match:
                    return False

                style_lines = re.findall(r'Style:.*', sub2_content)
                for i, line in enumerate(style_lines):
                    elements = line.split(',')
                    if len(elements) >= 3:
                        elements[2] = str(int(float(elements[2]) * fontSizeRatio))
                        style_lines[i] = ','.join(elements)

                events_start = sub2_content.find('[Events]')
                if events_start == -1:
                    return False

                events_content = sub2_content[events_start + len('[Events]'):].strip()
                output = os.path.splitext(sub2)[0] + ".withDanmu.ass"
                
                with open(output, 'w', encoding='utf-8-sig') as f:
                    f.write(sub1_content)
                    f.write('\n[V4+ Styles]\n')
                    f.write(format_match.group())
                    f.write('\n')
                    f.write('\n'.join(style_lines))
                    f.write('\n[Events]\n')
                    f.write(events_content)
                
                return True
                
            return False
            
        except Exception as e:
            logger.error(f"合并字幕失败: {e}")
            return False

def danmu_generator(file_path: str, width: int = 1920, height: int = 1080, 
                   fontface: str = 'Arial', fontsize: float = 50, 
                   alpha: float = 0.8, duration: float = 6, onlyFromBili: bool = False,
                   use_tmdb_id: bool = False, convert_t_2_s: bool = False, tmdb_id: Optional[int] = None,
                   episode: Optional[int] = None, subtitle_area_height: int = 200) -> Optional[str]:
    try:
        comment_id = DanmuAPI.get_comment_id(file_path, use_tmdb_id, tmdb_id, episode)
        if not comment_id:
            logger.info(f"未找到对应弹幕 - {file_path}")
            return None

        comments_data = DanmuAPI.get_comments(comment_id)
        if not comments_data:
            return None

        comments = sorted(comments_data["comments"], key=lambda x: float(x['p'].split(',')[0]))
        
        if len(comments) == 0:
            logger.info(f"弹幕数量为0，跳过生成 - {file_path}")
            return None

        # 过滤B站弹幕
        if onlyFromBili:
            comments = [comment for comment in comments if '[BiliBili]' in comment['p'].split(',')[3]]
            logger.info(f"过滤后剩余{len(comments)}条B站弹幕")

        output_file = os.path.splitext(file_path)[0] + '.danmu.ass'
        
        DanmuConverter.convert_comments_to_ass(
            comments, output_file, 
            width=int(width), 
            height=int(height), 
            fontface=fontface, 
            fontsize=float(fontsize), 
            alpha=float(alpha), 
            duration=float(duration),
            convert_t_2_s = convert_t_2_s,
            subtitle_area_height = subtitle_area_height
        )

        sub2 = SubtitleProcessor.find_subtitle_file(file_path)
        if not sub2:
            SubtitleProcessor.try_extract_sub(file_path)
            sub2 = SubtitleProcessor.find_subtitle_file(file_path)

        if sub2:
            SubtitleProcessor.combine_sub_ass(output_file, sub2)
        else:
            logger.error(f'未找到原生字幕，跳过合并 - {file_path}')

        return output_file

    except Exception as e:
        logger.error(f"生成弹幕失败: {e}")
        return None

